### PR TITLE
Db conditional

### PR DESCRIPTION
**Pull request by shanew**
These two patches make MySQL and SQLite3 support optional.

### CODE REVIEW

**Comment by jgarzik** [comment]
Review comments:
1) mysql commit #include's autotools-config.h with '<' and '>', which is inconsistent with all other source files.
2) other than that minor nit, mysql commit looks great, ACK overall design

3) sqlite3 m4 hardcodes /usr/lib in its search path, which is blatantly wrong for 64-bit Linux, resulting in the output seen here: http://paste.pocoo.org/show/367483/   Note the "-L/usr/lib" which is wrong for my 64-bit platform.

4) remove the "/*_/" comments from db-sqlite.c.  they serve no purpose, are inconsistent with other code, and create compiler warnings:
db-sqlite.c:101:24: warning: "/_" within comment
db-sqlite.c:101:29: warning: extra tokens at end of #endif directive

5) another example of #4, in server.h

6) other than those minor issues, sqlite change looks good, ACK overall design

7) it would make maintenance easier if you create an 'm4' directory, store each macro in an individual file in that directory, and update autogen.sh to add "-I m4" to aclocal execution.

**Comment by shanew** [comment]
Ok thanks for the pointers.

As an asside do you know if I can rebase changes without
nuking this branch and having to recreate a pull request.
Still on the git learning curve here.

**Comment by jgarzik** [comment]
git can force-update a remote branch.  You rebase locally, and then push to remote db-conditional branch.

If you rebase a branch, I -think- github will Do The Right Thing, and the pull request will automatically notice the rebase without problems.  I think.

**Comment by shanew** [comment]
Rebased

**Comment by jgarzik** [comment]
You missed items 4 and 5.  Corrected, and pulled.

Also, I liked the way the previous pull request split sqlite & mysql into two commits.  That is preferred over the one-big-commit approach.

**Pull request merged**
