### PR TITLE
Db sharelog

### PR DESCRIPTION
**Pull request by shanew**
Seeking review for potential inclusion
This adds the share logging support to PostGreSQL (tested) and SQLite (untested)
A couple minor fixes made along the way in seporate commits. I can break these out if you'd like.
database share logging is not exclusive so if you have database.sharelog defined as well as the name of a shares logfile, you get both.

### CODE REVIEW

**Comment by jgarzik** [comment]
Comments:

1) Commit 4c5561d is incorrect.  'our_result' may be a bool, but 'remote_result' has three states: Y, N, n/a.  The last state tells us that no share was submitted to upstream RPC.

2) Commit 4c5561d uses '0' and '1' for bool, which is inconsistent with the rest of the code.  Use 'true' and 'false' keywords.

3) Commit 126b461: ACK
4) Commit fc454f1: ACK
5) Commit d101876: ACK

6) Commit 190015f:  Be consistent with existing sqlite code.  Use sqlite3_bind_xxx rather than building a big SQL string.

Side note:  mysql should be using prepared statements and bound parameters also, rather than building an SQL string.  Not your problem, just pointing that out as a bad example, not to follow.

7) Commit 86c2df3: ACK

8) Commit f1b1fab: pg_sharelog() has a weird indentation.  otherwise ACK.

**Comment by shanew** [comment]
On Thu, Apr 07, 2011 at 09:41:36PM -0700, jgarzik wrote:

> 1) Commit 4c5561d is incorrect.  'our_result' may be a bool, but 'remote_result' has three states: Y, N, n/a.  The last state tells us that no share was submitted to upstream RPC.

Fixed, Though can this be true, false or NULL IN SQL?

> 6) Commit 190015f:  Be consistent with existing sqlite code.  Use sqlite3_bind_xxx rather than building a big SQL string.

I can do this but isn't that what sqlite3_mprintf
essentially does. Saves from having to call
sqlite3_bind_xxx and check result (6 times in this case).
The %Q allows us to insert null values, integer, chars etc
without caring about what is passed. That being said, not
the engine I use so I'm not the expert here.

Anyways, rebased but wanted to clarify your position on the
sqlite3_printf set of functions before doing that bit.

**Comment by jgarzik** [comment]
remote_result: I'm not sure that SQL can do true/false.  Traditionally the solution is char(1) with 'Y' or 'N', or NULL.

sqlite3_mprintf: Prepared statements + bind are far more efficient than repeatedly recompiling the same statement over and over again.  The sqlite code was written so that we could soon start compiling prepared statements in the sql_init() phase, leaving only the bind step for execution (pwdb lookup or sharelog write).  AFAIK, all three databases support this mode of operation.

Thus, using sqlite3_mprintf is moving in the opposite direction of what is intended, because we will want to use bind eventually anyway.  mprintf makes more work for ourselves, IMO.

**Comment by shanew** [comment]
On Fri, Apr 08, 2011 at 01:23:08AM -0700, jgarzik wrote:

> sqlite3_mprintf: Prepared statements + bind are far more efficient than repeatedly recompiling the same statement over and over again.  The sqlite code was written so that we could soon start compiling prepared statements in the sql_init() phase, leaving only the bind step for execution (pwdb lookup or sharelog write).  AFAIK, all three databases support this mode of operation.

Ok, it varies per engine then. PostGres is a bit different.
Quoting the manual:
From a performance standpoint, it is unwise to leave
transactions in
   the prepared state for a long time: this will for
instance interfere
   with the ability of VACUUM to reclaim storage. Keep in
mind also that
   the transaction continues to hold whatever locks it
held. The intended
   usage of the feature is that a prepared transaction will
normally be committed or rolled back as soon as an external
transaction manager has verified that other databases are
also prepared to commit.

That and PG has a query cache anyways and since insert is
not select and doesn't need to go through the planner,
well...

Sqlite is a different beast though so point taken.

**Pull request closed without merging**
